metatag.metatag_tag.taxonomy_page_sub_type:
  type: label
  label: 'Red Hat: Page Sub Type Taxonomy'
metatag.metatag_tag.taxonomy_product:
  type: label
  label: 'Red Hat: Product'
metatag.metatag_tag.taxonomy_product_line:
  type: label
  label: 'Red Hat: Product Line'
metatag.metatag_tag.taxonomy_topic:
  type: label
  label: 'Red Hat: Topic'
metatag.metatag_tag.node_type:
  type: label
  label: 'Red Hat: Node Type'
